name: MolScribe
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - jupyter
  - python=3.9
  - pytorch
  - torchvision
  - rdkit
  - pandas>=1.4.0
  - numpy>=1.22.0
  - matplotlib
  - tensorboardx
  - tqdm
  - seaborn
  - scipy
  - pip
  - pip:
    - opencv-python>=4.5.5.64
    - transformers>=4.5.1
    - SmilesPE==0.0.3
    - OpenNMT-py==2.2.0
    - albumentations==1.1.0
    - timm==0.5.4
